version: '3.4'

services:
  tmpuzzle:
    image: ${DOCKER_REGISTRY-}tmpuzzle
    build:
      context: .
      dockerfile: TmPuzzle/Dockerfile
    depends_on:
    - mssql
    environment:
    - ConnectionStrings__DefaultConnection=Server=mssql,1433;TrustServerCertificate=true;Database=TmPuzzle;User=sa;Password=hastalapasta123-hastalapasta456!
      
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "1433:1433"
    volumes:
        - ./data:/var/opt/mssql/data
        - ./log:/var/opt/mssql/log
        - ./secrets:/var/opt/mssql/secrets
    environment:
      - MSSQL_SA_PASSWORD=hastalapasta123-hastalapasta456!
      - ACCEPT_EULA=Y